# Generated by Django 3.1.3 on 2021-08-13 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='billing.invoice'),
        ),
    ]
